/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "isr_SleepTimer.h"
#include "SleepTimer.h"
#include "Power_VBAT1_aliases.h"
#include "Power_VBAT1.h"
#include "RTC.h"
#include "LED_aliases.h"
#include "LED.h"
#include "Power_VBAT2_aliases.h"
#include "Power_VBAT2.h"
#include "Power_VDD1_aliases.h"
#include "Power_VDD1.h"
#include "Power_VDD2_aliases.h"
#include "Power_VDD2.h"
#include "Power_VDD3_aliases.h"
#include "Power_VDD3.h"
#include "Power_VDD4_aliases.h"
#include "Power_VDD4.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

